; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.23026.0 

	TITLE	D:\cours\UQAC\Intelligence artificielle - jeux vidéos\Buckland_AISource\Common\misc\FrameCounter.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMTD
INCLUDELIB OLDNAMES

PUBLIC	??0FrameCounter@@AAE@XZ				; FrameCounter::FrameCounter
PUBLIC	?Instance@FrameCounter@@SAPAV1@XZ		; FrameCounter::Instance
EXTRN	__Init_thread_header:PROC
EXTRN	__Init_thread_footer:PROC
EXTRN	__RTC_CheckEsp:PROC
EXTRN	__RTC_InitBase:PROC
EXTRN	__RTC_Shutdown:PROC
EXTRN	__Init_thread_epoch:DWORD
EXTRN	__tls_array:DWORD
EXTRN	__tls_index:DWORD
;	COMDAT ?instance@?1??Instance@FrameCounter@@SAPAV2@XZ@4V2@A
_BSS	SEGMENT
?instance@?1??Instance@FrameCounter@@SAPAV2@XZ@4V2@A DQ 01H DUP (?) ; `FrameCounter::Instance'::`2'::instance
_BSS	ENDS
;	COMDAT ?$TSS0@?1??Instance@FrameCounter@@SAPAV2@XZ@4HA
_BSS	SEGMENT
?$TSS0@?1??Instance@FrameCounter@@SAPAV2@XZ@4HA DD 01H DUP (?) ; TSS0<`template-parameter-2',FrameCounter::stance,FrameCounter * * const volatile,void,int, ?? &>
_BSS	ENDS
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
rtc$IMZ	ENDS
; Function compile flags: /Odtp /RTCsu
; File d:\cours\uqac\intelligence artificielle - jeux vidéos\buckland_aisource\common\misc\framecounter.cpp
_TEXT	SEGMENT
?Instance@FrameCounter@@SAPAV1@XZ PROC			; FrameCounter::Instance

; 5    : {

	push	ebp
	mov	ebp, esp

; 6    :   static FrameCounter instance;

	mov	eax, DWORD PTR __tls_index
	mov	ecx, DWORD PTR fs:__tls_array
	mov	edx, DWORD PTR [ecx+eax*4]
	mov	eax, DWORD PTR ?$TSS0@?1??Instance@FrameCounter@@SAPAV2@XZ@4HA
	cmp	eax, DWORD PTR __Init_thread_epoch[edx]
	jle	SHORT $LN2@Instance
	push	OFFSET ?$TSS0@?1??Instance@FrameCounter@@SAPAV2@XZ@4HA
	call	__Init_thread_header
	add	esp, 4
	cmp	DWORD PTR ?$TSS0@?1??Instance@FrameCounter@@SAPAV2@XZ@4HA, -1
	jne	SHORT $LN2@Instance
	mov	ecx, OFFSET ?instance@?1??Instance@FrameCounter@@SAPAV2@XZ@4V2@A
	call	??0FrameCounter@@AAE@XZ			; FrameCounter::FrameCounter
	push	OFFSET ?$TSS0@?1??Instance@FrameCounter@@SAPAV2@XZ@4HA
	call	__Init_thread_footer
	add	esp, 4
$LN2@Instance:

; 7    : 
; 8    :   return &instance;

	mov	eax, OFFSET ?instance@?1??Instance@FrameCounter@@SAPAV2@XZ@4V2@A

; 9    : }

	cmp	ebp, esp
	call	__RTC_CheckEsp
	pop	ebp
	ret	0
?Instance@FrameCounter@@SAPAV1@XZ ENDP			; FrameCounter::Instance
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu
; File d:\cours\uqac\intelligence artificielle - jeux vidéos\buckland_aisource\common\misc\framecounter.h
;	COMDAT ??0FrameCounter@@AAE@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
??0FrameCounter@@AAE@XZ PROC				; FrameCounter::FrameCounter, COMDAT
; _this$ = ecx

; 15   :   FrameCounter():m_lCount(0), m_iFramesElapsed(0){}

	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR [ebp-4], -858993460		; ccccccccH
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax], 0
	mov	ecx, DWORD PTR _this$[ebp]
	mov	DWORD PTR [ecx+4], 0
	mov	eax, DWORD PTR _this$[ebp]
	mov	esp, ebp
	pop	ebp
	ret	0
??0FrameCounter@@AAE@XZ ENDP				; FrameCounter::FrameCounter
_TEXT	ENDS
END
