; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.23026.0 

	TITLE	D:\cours\UQAC\Intelligence artificielle - jeux vidéos\Buckland_AISource\Mini_Projet_Raven\Raven_UserOptions.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMTD
INCLUDELIB OLDNAMES

PUBLIC	??0Raven_UserOptions@@AAE@XZ			; Raven_UserOptions::Raven_UserOptions
PUBLIC	?Instance@Raven_UserOptions@@SAPAV1@XZ		; Raven_UserOptions::Instance
EXTRN	__Init_thread_header:PROC
EXTRN	__Init_thread_footer:PROC
EXTRN	__RTC_CheckEsp:PROC
EXTRN	__RTC_InitBase:PROC
EXTRN	__RTC_Shutdown:PROC
EXTRN	__Init_thread_epoch:DWORD
EXTRN	__tls_array:DWORD
EXTRN	__tls_index:DWORD
;	COMDAT ?instance@?1??Instance@Raven_UserOptions@@SAPAV2@XZ@4V2@A
_BSS	SEGMENT
?instance@?1??Instance@Raven_UserOptions@@SAPAV2@XZ@4V2@A DB 0eH DUP (?) ; `Raven_UserOptions::Instance'::`2'::instance
_BSS	ENDS
;	COMDAT ?$TSS0@?1??Instance@Raven_UserOptions@@SAPAV2@XZ@4HA
_BSS	SEGMENT
?$TSS0@?1??Instance@Raven_UserOptions@@SAPAV2@XZ@4HA DD 01H DUP (?) ; TSS0<`template-parameter-2',Raven_UserOptions::stance,Raven_UserOptions * * const volatile,void,int, ?? &>
_BSS	ENDS
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
rtc$IMZ	ENDS
; Function compile flags: /Odtp /RTCsu
; File d:\cours\uqac\intelligence artificielle - jeux vidéos\buckland_aisource\mini_projet_raven\raven_useroptions.cpp
_TEXT	SEGMENT
?Instance@Raven_UserOptions@@SAPAV1@XZ PROC		; Raven_UserOptions::Instance

; 5    : {

	push	ebp
	mov	ebp, esp

; 6    :   static Raven_UserOptions instance; 

	mov	eax, DWORD PTR __tls_index
	mov	ecx, DWORD PTR fs:__tls_array
	mov	edx, DWORD PTR [ecx+eax*4]
	mov	eax, DWORD PTR ?$TSS0@?1??Instance@Raven_UserOptions@@SAPAV2@XZ@4HA
	cmp	eax, DWORD PTR __Init_thread_epoch[edx]
	jle	SHORT $LN2@Instance
	push	OFFSET ?$TSS0@?1??Instance@Raven_UserOptions@@SAPAV2@XZ@4HA
	call	__Init_thread_header
	add	esp, 4
	cmp	DWORD PTR ?$TSS0@?1??Instance@Raven_UserOptions@@SAPAV2@XZ@4HA, -1
	jne	SHORT $LN2@Instance
	mov	ecx, OFFSET ?instance@?1??Instance@Raven_UserOptions@@SAPAV2@XZ@4V2@A
	call	??0Raven_UserOptions@@AAE@XZ		; Raven_UserOptions::Raven_UserOptions
	push	OFFSET ?$TSS0@?1??Instance@Raven_UserOptions@@SAPAV2@XZ@4HA
	call	__Init_thread_footer
	add	esp, 4
$LN2@Instance:

; 7    :   return &instance;

	mov	eax, OFFSET ?instance@?1??Instance@Raven_UserOptions@@SAPAV2@XZ@4V2@A

; 8    : }

	cmp	ebp, esp
	call	__RTC_CheckEsp
	pop	ebp
	ret	0
?Instance@Raven_UserOptions@@SAPAV1@XZ ENDP		; Raven_UserOptions::Instance
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu
; File d:\cours\uqac\intelligence artificielle - jeux vidéos\buckland_aisource\mini_projet_raven\raven_useroptions.cpp
_TEXT	SEGMENT
_this$ = -4						; size = 4
??0Raven_UserOptions@@AAE@XZ PROC			; Raven_UserOptions::Raven_UserOptions
; _this$ = ecx

; 24   : {}

	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR [ebp-4], -858993460		; ccccccccH
	mov	DWORD PTR _this$[ebp], ecx

; 10   : Raven_UserOptions::Raven_UserOptions():m_bShowGraph(false),

	mov	eax, DWORD PTR _this$[ebp]
	mov	BYTE PTR [eax], 0

; 21   :                       m_bShowNodeIndices(false),

	mov	ecx, DWORD PTR _this$[ebp]
	mov	BYTE PTR [ecx+1], 0

; 11   :                       m_bShowPathOfSelectedBot(true),

	mov	edx, DWORD PTR _this$[ebp]
	mov	BYTE PTR [edx+2], 1

; 16   :                       m_bShowTargetOfSelectedBot(false),

	mov	eax, DWORD PTR _this$[ebp]
	mov	BYTE PTR [eax+3], 0

; 22   :                       m_bShowOpponentsSensedBySelectedBot(true),

	mov	ecx, DWORD PTR _this$[ebp]
	mov	BYTE PTR [ecx+4], 1

; 17   :                       m_bOnlyShowBotsInTargetsFOV(false),

	mov	edx, DWORD PTR _this$[ebp]
	mov	BYTE PTR [edx+5], 0

; 19   :                       m_bShowGoalsOfSelectedBot(true),

	mov	eax, DWORD PTR _this$[ebp]
	mov	BYTE PTR [eax+6], 1

; 20   :                       m_bShowGoalAppraisals(true),

	mov	ecx, DWORD PTR _this$[ebp]
	mov	BYTE PTR [ecx+7], 1

; 23   :                       m_bShowWeaponAppraisals(false)

	mov	edx, DWORD PTR _this$[ebp]
	mov	BYTE PTR [edx+8], 0

; 12   :                       m_bSmoothPathsQuick(false),

	mov	eax, DWORD PTR _this$[ebp]
	mov	BYTE PTR [eax+9], 0

; 13   :                       m_bSmoothPathsPrecise(false),

	mov	ecx, DWORD PTR _this$[ebp]
	mov	BYTE PTR [ecx+10], 0

; 14   :                       m_bShowBotIDs(false),

	mov	edx, DWORD PTR _this$[ebp]
	mov	BYTE PTR [edx+11], 0

; 15   :                       m_bShowBotHealth(true),

	mov	eax, DWORD PTR _this$[ebp]
	mov	BYTE PTR [eax+12], 1

; 18   :                       m_bShowScore(false),

	mov	ecx, DWORD PTR _this$[ebp]
	mov	BYTE PTR [ecx+13], 0

; 24   : {}

	mov	eax, DWORD PTR _this$[ebp]
	mov	esp, ebp
	pop	ebp
	ret	0
??0Raven_UserOptions@@AAE@XZ ENDP			; Raven_UserOptions::Raven_UserOptions
_TEXT	ENDS
END
